
<div id="footer">
	<img src="images/loghi.png" />
        <ul>
                <li class="copyright">GIAMPIERO GIGANTE, C.so Nazario Sauro 6 18038 Sanremo P.iva 0123456789 | progetto <a href="http://www.freementi.it">FREEmenti</a></li>			
                <li><a href="#" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#" target="_blank" title="Pinterest"><i class="fa fa-pinterest"></i></li>
        </ul>
</div>