
<div id="footer">

        <ul id="brands">
                <li ><a href="https://w.wella.com/" target="_blank"><img src="images/brands/wella.png" /></a></li>			
                <li><a href="http://www.tigiprofessional.com/it-it" target="_blank" ><img src="images/brands/tigi.png" /></a></li>
                <li><a href="http://www.ghdhair.com/it/" target="_blank" ><img src="images/brands/gdh.png" /></a></li>
                <li><a href="http://www.paulmitchell.it/" target="_blank" ><img src="images/brands/mitchell.png" /></a></li>
                <li><a href="http://www.greatlengths.net/" target="_blank" ><img src="images/brands/greatlenghts.png" /></a></li>
        </ul>
	
        <ul>
                <li class="copyright">GIAMPIERO GIGANTE, C.so Orazio Raimondo 1, 18038 Sanremo P.iva 01027440088 | progetto <a href="http://www.freementi.it">FREEmenti</a></li>			
                <li><a href="#" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://twitter.com/share" class="twitter-share-button" data-text="Giampiero Gigante Hair and Beauty" data-lang="it" data-count="none"><i class="fa fa-twitter"></i></a></li>
                <li><a href="//it.pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.giampierogigante.it&media=http://www.giampierogigante.it/new/images/home/home_1.jpg&description=Giampiero Gigante Hair and beauty" data-pin-do="buttonPin" data-pin-config="above"><i class="fa fa-pinterest"></i></a></li>
        </ul>


</div>