<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]--> 
<!--[if IE 9 ]>    <html lang="en" class="ie"> <![endif]--> 
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<head>

	<!-- INIZIO Dichiarazioni Comuni -->
	
	<meta charset="utf-8" />
    <title>Giampiero Gigante | Hair and beauty | parrucchiere Sanremo</title>
    <meta name="description" content="Html - jQuery template by pezflash" />
   	<meta name="keywords" content="" />
    <meta name="robots" content="index, follow" />
       
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic" />
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="js/vegas/jquery.vegas.css" />
    <link rel="stylesheet" type="text/css" href="js/tipsy/tipsy.css" />
  	<link rel="stylesheet" type="text/css" href="js/prettyPhoto/css/prettyPhoto.css" media="all" />
    <link rel="stylesheet" type="text/css" href="js/superfish/superfish.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="css/styles.css" />
    
    <script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="js/vegas/jquery.vegas.js"></script>
	<script type="text/javascript" src="js/vegas/vegas.fullscreen.config.js"></script>
    <script type="text/javascript" src="js/tipsy/jquery.tipsy.js"></script>
    <script type="text/javascript" src="js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="js/superfish/hoverIntent.js"></script>
    <script type="text/javascript" src="js/superfish/superfish.js"></script>
   	<script type="text/javascript" src="js/mdetect.js"></script>
   	<script type="text/javascript" src="js/global.js"></script>

	<!-- FINE Dichiarazioni Comuni -->
        

	
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
